package com.example.bbltripplanner.screens.userTrip.entity

import com.google.gson.annotations.SerializedName

enum class Currency(
    val code: String,
    val symbol: String
) {
    @SerializedName("AED") AED("AED","د.إ"),
    @SerializedName("AFN") AFN("AFN","؋"),
    @SerializedName("ALL") ALL("ALL","L"),
    @SerializedName("AMD") AMD("AMD","֏"),
    @SerializedName("ANG") ANG("ANG","ƒ"),
    @SerializedName("AOA") AOA("AOA","Kz"),
    @SerializedName("ARS") ARS("ARS","$"),
    @SerializedName("AUD") AUD("AUD","$"),
    @SerializedName("AWG") AWG("AWG","ƒ"),
    @SerializedName("AZN") AZN("AZN","₼"),

    @SerializedName("BAM") BAM("BAM","KM"),
    @SerializedName("BBD") BBD("BBD","$"),
    @SerializedName("BDT") BDT("BDT","৳"),
    @SerializedName("BGN") BGN("BGN","лв"),
    @SerializedName("BHD") BHD("BHD",".د.ب"),
    @SerializedName("BIF") BIF("BIF","FBu"),
    @SerializedName("BMD") BMD("BMD","$"),
    @SerializedName("BND") BND("BND","$"),
    @SerializedName("BOB") BOB("BOB","Bs."),
    @SerializedName("BOV") BOV("BOV","BOV"),
    @SerializedName("BRL") BRL("BRL","R$"),
    @SerializedName("BSD") BSD("BSD","$"),
    @SerializedName("BTN") BTN("BTN","Nu."),
    @SerializedName("BWP") BWP("BWP","P"),
    @SerializedName("BYN") BYN("BYN","Br"),
    @SerializedName("BZD") BZD("BZD","$"),

    @SerializedName("CAD") CAD("CAD","$"),
    @SerializedName("CDF") CDF("CDF","FC"),
    @SerializedName("CHE") CHE("CHE","CHE"),
    @SerializedName("CHF") CHF("CHF","CHF"),
    @SerializedName("CHW") CHW("CHW","CHW"),
    @SerializedName("CLF") CLF("CLF","UF"),
    @SerializedName("CLP") CLP("CLP","$"),
    @SerializedName("CNY") CNY("CNY","¥"),
    @SerializedName("COP") COP("COP","$"),
    @SerializedName("COU") COU("COU","COU"),
    @SerializedName("CRC") CRC("CRC","₡"),
    @SerializedName("CUC") CUC("CUC","$"),
    @SerializedName("CUP") CUP("CUP","₱"),
    @SerializedName("CVE") CVE("CVE","$"),
    @SerializedName("CZK") CZK("CZK","Kč"),

    @SerializedName("DJF") DJF("DJF","Fdj"),
    @SerializedName("DKK") DKK("DKK","kr"),
    @SerializedName("DOP") DOP("DOP","RD$"),
    @SerializedName("DZD") DZD("DZD","دج"),

    @SerializedName("EGP") EGP("EGP","£"),
    @SerializedName("ERN") ERN("ERN","Nfk"),
    @SerializedName("ETB") ETB("ETB","Br"),
    @SerializedName("EUR") EUR("EUR","€"),

    @SerializedName("FJD") FJD("FJD","$"),
    @SerializedName("FKP") FKP("FKP","£"),

    @SerializedName("GBP") GBP("GBP","£"),
    @SerializedName("GEL") GEL("GEL","₾"),
    @SerializedName("GHS") GHS("GHS","₵"),
    @SerializedName("GIP") GIP("GIP","£"),
    @SerializedName("GMD") GMD("GMD","D"),
    @SerializedName("GNF") GNF("GNF","FG"),
    @SerializedName("GTQ") GTQ("GTQ","Q"),
    @SerializedName("GYD") GYD("GYD","$"),

    @SerializedName("HKD") HKD("HKD","$"),
    @SerializedName("HNL") HNL("HNL","L"),
    @SerializedName("HTG") HTG("HTG","G"),
    @SerializedName("HUF") HUF("HUF","Ft"),

    @SerializedName("IDR") IDR("IDR","Rp"),
    @SerializedName("ILS") ILS("ILS","₪"),
    @SerializedName("INR") INR("INR","₹"),
    @SerializedName("IQD") IQD("IQD","ع.د"),
    @SerializedName("IRR") IRR("IRR","﷼"),
    @SerializedName("ISK") ISK("ISK","kr"),

    @SerializedName("JMD") JMD("JMD","$"),
    @SerializedName("JOD") JOD("JOD","د.ا"),
    @SerializedName("JPY") JPY("JPY","¥"),

    @SerializedName("KES") KES("KES","KSh"),
    @SerializedName("KGS") KGS("KGS","с"),
    @SerializedName("KHR") KHR("KHR","៛"),
    @SerializedName("KMF") KMF("KMF","CF"),
    @SerializedName("KPW") KPW("KPW","₩"),
    @SerializedName("KRW") KRW("KRW","₩"),
    @SerializedName("KWD") KWD("KWD","د.ك"),
    @SerializedName("KYD") KYD("KYD","$"),
    @SerializedName("KZT") KZT("KZT","₸"),

    @SerializedName("LAK") LAK("LAK","₭"),
    @SerializedName("LBP") LBP("LBP","£"),
    @SerializedName("LKR") LKR("LKR","₨"),
    @SerializedName("LRD") LRD("LRD","$"),
    @SerializedName("LSL") LSL("LSL","L"),
    @SerializedName("LYD") LYD("LYD","ل.د"),

    @SerializedName("MAD") MAD("MAD","د.م."),
    @SerializedName("MDL") MDL("MDL","L"),
    @SerializedName("MGA") MGA("MGA","Ar"),
    @SerializedName("MKD") MKD("MKD","ден"),
    @SerializedName("MMK") MMK("MMK","Ks"),
    @SerializedName("MNT") MNT("MNT","₮"),
    @SerializedName("MOP") MOP("MOP","P"),
    @SerializedName("MRU") MRU("MRU","UM"),
    @SerializedName("MUR") MUR("MUR","₨"),
    @SerializedName("MVR") MVR("MVR","Rf"),
    @SerializedName("MWK") MWK("MWK","MK"),
    @SerializedName("MXN") MXN("MXN","$"),
    @SerializedName("MXV") MXV("MXV","MXV"),
    @SerializedName("MYR") MYR("MYR","RM"),
    @SerializedName("MZN") MZN("MZN","MT"),

    @SerializedName("NAD") NAD("NAD","$"),
    @SerializedName("NGN") NGN("NGN","₦"),
    @SerializedName("NIO") NIO("NIO","C$"),
    @SerializedName("NOK") NOK("NOK","kr"),
    @SerializedName("NPR") NPR("NPR","₨"),
    @SerializedName("NZD") NZD("NZD","$"),

    @SerializedName("OMR") OMR("OMR","﷼"),

    @SerializedName("PAB") PAB("PAB","B/."),
    @SerializedName("PEN") PEN("PEN","S/"),
    @SerializedName("PGK") PGK("PGK","K"),
    @SerializedName("PHP") PHP("PHP","₱"),
    @SerializedName("PKR") PKR("PKR","₨"),
    @SerializedName("PLN") PLN("PLN","zł"),
    @SerializedName("PYG") PYG("PYG","₲"),

    @SerializedName("QAR") QAR("QAR","﷼"),

    @SerializedName("RON") RON("RON","lei"),
    @SerializedName("RSD") RSD("RSD","дин."),
    @SerializedName("RUB") RUB("RUB","₽"),
    @SerializedName("RWF") RWF("RWF","FRw"),

    @SerializedName("SAR") SAR("SAR","﷼"),
    @SerializedName("SBD") SBD("SBD","$"),
    @SerializedName("SCR") SCR("SCR","₨"),
    @SerializedName("SDG") SDG("SDG","£"),
    @SerializedName("SEK") SEK("SEK","kr"),
    @SerializedName("SGD") SGD("SGD","$"),
    @SerializedName("SHP") SHP("SHP","£"),
    @SerializedName("SLE") SLE("SLE","Le"),
    @SerializedName("SLL") SLL("SLL","Le"),
    @SerializedName("SOS") SOS("SOS","Sh"),
    @SerializedName("SRD") SRD("SRD","$"),
    @SerializedName("SSP") SSP("SSP","£"),
    @SerializedName("STN") STN("STN","Db"),
    @SerializedName("SVC") SVC("SVC","$"),
    @SerializedName("SYP") SYP("SYP","£"),
    @SerializedName("SZL") SZL("SZL","L"),

    @SerializedName("THB") THB("THB","฿"),
    @SerializedName("TJS") TJS("TJS","ЅМ"),
    @SerializedName("TMT") TMT("TMT","m"),
    @SerializedName("TND") TND("TND","د.ت"),
    @SerializedName("TOP") TOP("TOP","T$"),
    @SerializedName("TRY") TRY("TRY","₺"),
    @SerializedName("TTD") TTD("TTD","$"),
    @SerializedName("TWD") TWD("TWD","NT$"),
    @SerializedName("TZS") TZS("TZS","Sh"),

    @SerializedName("UAH") UAH("UAH","₴"),
    @SerializedName("UGX") UGX("UGX","Sh"),
    @SerializedName("USD") USD("USD","$"),
    @SerializedName("USN") USN("USN","USN"),
    @SerializedName("UYI") UYI("UYI","UYI"),
    @SerializedName("UYU") UYU("UYU","$"),
    @SerializedName("UZS") UZS("UZS","so'm"),

    @SerializedName("VED") VED("VED","Bs"),
    @SerializedName("VES") VES("VES","Bs"),
    @SerializedName("VND") VND("VND","₫"),
    @SerializedName("VUV") VUV("VUV","VT"),

    @SerializedName("WST") WST("WST","T"),

    @SerializedName("XAF") XAF("XAF","FCFA"),
    @SerializedName("XAG") XAG("XAG","XAG"),
    @SerializedName("XAU") XAU("XAU","XAU"),
    @SerializedName("XBA") XBA("XBA","XBA"),
    @SerializedName("XBB") XBB("XBB","XBB"),
    @SerializedName("XBC") XBC("XBC","XBC"),
    @SerializedName("XBD") XBD("XBD","XBD"),
    @SerializedName("XCD") XCD("XCD","$"),
    @SerializedName("XDR") XDR("XDR","XDR"),
    @SerializedName("XOF") XOF("XOF","CFA"),
    @SerializedName("XPD") XPD("XPD","XPD"),
    @SerializedName("XPF") XPF("XPF","₣"),
    @SerializedName("XPT") XPT("XPT","XPT"),
    @SerializedName("XSU") XSU("XSU","XSU"),
    @SerializedName("XTS") XTS("XTS","XTS"),
    @SerializedName("XUA") XUA("XUA","XUA"),
    @SerializedName("XXX") XXX("XXX",""),

    @SerializedName("YER") YER("YER","﷼"),

    @SerializedName("ZAR") ZAR("ZAR","R"),
    @SerializedName("ZMW") ZMW("ZMW","ZK"),
    @SerializedName("ZWL") ZWL("ZWL","$")
}